"""Initial migration

Revision ID: bf2190783f23
Revises: 
Create Date: 2024-08-31 11:41:53.852281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf2190783f23'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broker',
    sa.Column('Id_Broker', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Nombre', sa.String(length=60), nullable=False),
    sa.Column('Comision', sa.Float(), nullable=False),
    sa.Column('Asesor', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('Id_Broker')
    )
    op.create_table('instrumento_financiero',
    sa.Column('Id_InstrumentoFinanciero', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Nombre', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('Id_InstrumentoFinanciero')
    )
    op.create_table('comitente',
    sa.Column('Id_Comitente', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Titular', sa.String(length=60), nullable=False),
    sa.Column('Numero', sa.Integer(), nullable=False),
    sa.Column('Id_Broker', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Id_Broker'], ['broker.Id_Broker'], ),
    sa.PrimaryKeyConstraint('Id_Comitente')
    )
    op.create_table('ticker',
    sa.Column('Id_Ticker', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Nombre_Ticker', sa.String(length=60), nullable=False),
    sa.Column('Descripcion', sa.String(length=60), nullable=False),
    sa.Column('Id_InstrumentoFinanciero', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Id_InstrumentoFinanciero'], ['instrumento_financiero.Id_InstrumentoFinanciero'], ),
    sa.PrimaryKeyConstraint('Id_Ticker')
    )
    op.create_table('compra',
    sa.Column('Id_Compra', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Id_Broker', sa.Integer(), nullable=False),
    sa.Column('Id_Comitente', sa.Integer(), nullable=False),
    sa.Column('Id_Ticker', sa.Integer(), nullable=False),
    sa.Column('Precio_Dolar_MEP', sa.Float(), nullable=False),
    sa.Column('Fecha_Hora', sa.DateTime(), nullable=False),
    sa.Column('Precio_Compra', sa.Float(), nullable=False),
    sa.Column('Cantidad_Nominales', sa.Float(), nullable=False),
    sa.Column('Comision_Broker', sa.Float(), nullable=False),
    sa.Column('Total_Pesos', sa.Float(), nullable=False),
    sa.Column('Total_Dolares', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['Id_Broker'], ['broker.Id_Broker'], ),
    sa.ForeignKeyConstraint(['Id_Comitente'], ['comitente.Id_Comitente'], ),
    sa.ForeignKeyConstraint(['Id_Ticker'], ['ticker.Id_Ticker'], ),
    sa.PrimaryKeyConstraint('Id_Compra')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('compra')
    op.drop_table('ticker')
    op.drop_table('comitente')
    op.drop_table('instrumento_financiero')
    op.drop_table('broker')
    # ### end Alembic commands ###
