"""Renombrar el campo id_compra a id_activo tabla activo

Revision ID: c7bdc8e42d20
Revises: bf2190783f23
Create Date: 2024-09-09 18:32:44.662057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7bdc8e42d20'
down_revision = 'bf2190783f23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activo',
    sa.Column('Id_Activo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Id_Broker', sa.Integer(), nullable=False),
    sa.Column('Id_Comitente', sa.Integer(), nullable=False),
    sa.Column('Id_Ticker', sa.Integer(), nullable=False),
    sa.Column('Precio_Dolar_MEP_Compra', sa.Float(), nullable=False),
    sa.Column('Fecha_Hora_Compra', sa.DateTime(), nullable=False),
    sa.Column('Precio_Compra', sa.Float(), nullable=False),
    sa.Column('Cantidad_Nominales_Compra', sa.Float(), nullable=False),
    sa.Column('Comision_Broker', sa.Float(), nullable=False),
    sa.Column('Total_Pesos_Compra', sa.Float(), nullable=False),
    sa.Column('Total_Dolares_Compra', sa.Float(), nullable=False),
    sa.Column('Precio_Dolar_MEP_Venta', sa.Float(), nullable=True),
    sa.Column('Fecha_Hora_Venta', sa.DateTime(), nullable=True),
    sa.Column('Precio_Venta', sa.Float(), nullable=True),
    sa.Column('Cantidad_Nominales_Venta', sa.Float(), nullable=True),
    sa.Column('Total_Pesos_Venta', sa.Float(), nullable=True),
    sa.Column('Total_Dolares_Venta', sa.Float(), nullable=True),
    sa.Column('Activo_Estado', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['Id_Broker'], ['broker.Id_Broker'], ),
    sa.ForeignKeyConstraint(['Id_Comitente'], ['comitente.Id_Comitente'], ),
    sa.ForeignKeyConstraint(['Id_Ticker'], ['ticker.Id_Ticker'], ),
    sa.PrimaryKeyConstraint('Id_Activo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activo')
    # ### end Alembic commands ###
